module.exports = [
  {
    id: 1,
    username: "random_user_123",
    first_name: "John",
    last_name: "Doe",
    phone_number: "+440000000000",
    email: "john.doe@example.com",
    password: "randompassword",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    username: "user456",
    first_name: "Jane",
    last_name: "Smith",
    phone_number: "+441111111111",
    email: "jane.smith@example.com",
    password: "secure123",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 3,
    username: "awesome_user",
    first_name: "Michael",
    last_name: "Johnson",
    phone_number: "+442222222222",
    email: "michael.j@example.com",
    password: "myp@ssw0rd",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    username: "user789",
    first_name: "Emily",
    last_name: "Davis",
    phone_number: "+443333333333",
    email: "emily.d@example.com",
    password: "p@ssw0rd123",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 5,
    username: "random_user_567",
    first_name: "Robert",
    last_name: "Taylor",
    phone_number: "+444444444444",
    email: "robert.t@example.com",
    password: "randompass567",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 6,
    username: "user012",
    first_name: "Sophia",
    last_name: "Brown",
    phone_number: "+445555555555",
    email: "sophia.b@example.com",
    password: "secure789",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 7,
    username: "cool_user",
    first_name: "David",
    last_name: "Williams",
    phone_number: "+446666666666",
    email: "david.w@example.com",
    password: "myp@ssw0rd789",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    username: "user234",
    first_name: "Olivia",
    last_name: "Miller",
    phone_number: "+447777777777",
    email: "olivia.m@example.com",
    password: "p@ssw0rd234",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    username: "random_user_890",
    first_name: "William",
    last_name: "Anderson",
    phone_number: "+448888888888",
    email: "william.a@example.com",
    password: "randompass890",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    username: "user345",
    first_name: "Emma",
    last_name: "Wilson",
    phone_number: "+449999999999",
    email: "emma.w@example.com",
    password: "secure012",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    username: "awesome_user_2",
    first_name: "Daniel",
    last_name: "Thomas",
    phone_number: "+440000000011",
    email: "daniel.t@example.com",
    password: "myp@ssw0rd2",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    username: "user567",
    first_name: "Ava",
    last_name: "Moore",
    phone_number: "+440000000022",
    email: "ava.m@example.com",
    password: "p@ssw0rd567",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    username: "user_3",
    first_name: "Matthew",
    last_name: "White",
    phone_number: "+440000000033",
    email: "matthew.w@example.com",
    password: "randompass3",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    username: "user678",
    first_name: "Ella",
    last_name: "Jones",
    phone_number: "+440000000044",
    email: "ella.j@example.com",
    password: "secure789",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    username: "random_user_456",
    first_name: "Christopher",
    last_name: "Davis",
    phone_number: "+440000000055",
    email: "christopher.d@example.com",
    password: "myp@ssw0rd456",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 16,
    username: "user789_2",
    first_name: "Mia",
    last_name: "Moore",
    phone_number: "+440000000066",
    email: "mia.m@example.com",
    password: "p@ssw0rd7892",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 17,
    username: "cool_user_2",
    first_name: "Andrew",
    last_name: "Taylor",
    phone_number: "+440000000077",
    email: "andrew.t@example.com",
    password: "myp@ssw0rd2",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    id: 18,
    username: "user890",
    first_name: "Avery",
    last_name: "Johnson",
    phone_number: "+440000000088",
    email: "avery.j@example.com",
    password: "p@ssw0rd890",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 19,
    username: "random_user_789",
    first_name: "James",
    last_name: "Wilson",
    phone_number: "+440000000099",
    email: "james.w@example.com",
    password: "randompass789",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    id: 20,
    username: "user123",
    first_name: "Sofia",
    last_name: "Anderson",
    phone_number: "+440000000100",
    email: "sofia.a@example.com",
    password: "secure123",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
  },
];
