module.exports = [
  {
    id: 1,
    username: "random_user_1",
    first_name: "Alice",
    last_name: "Johnson",
    phone_number: "+441111111111",
    email: "alice.johnson@example.com",
    role: "standard_user",
    password: "randompassword1",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 2,
    username: "random_user_2",
    first_name: "Bob",
    last_name: "Smith",
    phone_number: "+442222222222",
    email: "bob.smith@example.com",
    role: "standard_user",
    password: "randompassword2",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 3,
    username: "random_user_3",
    first_name: "Eva",
    last_name: "Williams",
    phone_number: "+443333333333",
    email: "eva.williams@example.com",
    role: "standard_user",
    password: "randompassword3",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 4,
    username: "random_user_4",
    first_name: "Daniel",
    last_name: "Miller",
    phone_number: "+444444444444",
    email: "daniel.miller@example.com",
    role: "standard_user",
    password: "randompassword4",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 5,
    username: "random_user_5",
    first_name: "Grace",
    last_name: "Davis",
    phone_number: "+445555555555",
    email: "grace.davis@example.com",
    role: "standard_user",
    password: "randompassword5",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 6,
    username: "random_user_6",
    first_name: "Frank",
    last_name: "Johnson",
    phone_number: "+446666666666",
    email: "frank.johnson@example.com",
    role: "standard_user",
    password: "randompassword6",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    username: "random_user_7",
    first_name: "Sophia",
    last_name: "Lee",
    phone_number: "+447777777777",
    email: "sophia.lee@example.com",
    role: "standard_user",
    password: "randompassword7",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    username: "random_user_8",
    first_name: "Mark",
    last_name: "Taylor",
    phone_number: "+448888888888",
    email: "mark.taylor@example.com",
    role: "standard_user",
    password: "randompassword8",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    username: "random_user_9",
    first_name: "Olivia",
    last_name: "Clark",
    phone_number: "+449999999999",
    email: "olivia.clark@example.com",
    role: "standard_user",
    password: "randompassword9",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    username: "random_user_10",
    first_name: "Peter",
    last_name: "Brown",
    phone_number: "+440101010101",
    email: "peter.brown@example.com",
    role: "standard_user",
    password: "randompassword10",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 11,
    username: "random_user_11",
    first_name: "Emily",
    last_name: "Anderson",
    phone_number: "+440202020202",
    email: "emily.anderson@example.com",
    role: "standard_user",
    password: "randompassword11",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 12,
    username: "random_user_12",
    first_name: "Michael",
    last_name: "Moore",
    phone_number: "+440303030303",
    email: "michael.moore@example.com",
    role: "standard_user",
    password: "randompassword12",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 13,
    username: "random_user_13",
    first_name: "Lily",
    last_name: "White",
    phone_number: "+440404040404",
    email: "lily.white@example.com",
    role: "standard_user",
    password: "randompassword13",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 14,
    username: "random_user_14",
    first_name: "Christopher",
    last_name: "King",
    phone_number: "+440505050505",
    email: "christopher.king@example.com",
    role: "standard_user",
    password: "randompassword14",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 15,
    username: "random_user_15",
    first_name: "Ava",
    last_name: "Johnson",
    phone_number: "+440606060606",
    email: "ava.johnson@example.com",
    role: "standard_user",
    password: "randompassword15",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: 16,
    username: "random_user_16",
    first_name: "David",
    last_name: "Brown",
    phone_number: "+440707070707",
    email: "david.brown@example.com",
    role: "standard_user",
    password: "randompassword16",
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: 17,
    username: "random_user_17",
    first_name: "Sophie",
    last_name: "Taylor",
    phone_number: "+440808080808",
    email: "sophie.taylor@example.com",
    role: "standard_user",
    password: "randompassword17",
    avatar: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: 18,
    username: "random_user_18",
    first_name: "Matthew",
    last_name: "Miller",
    phone_number: "+440909090909",
    email: "matthew.miller@example.com",
    role: "standard_user",
    password: "randompassword18",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: 19,
    username: "random_user_19",
    first_name: "Emma",
    last_name: "Davis",
    phone_number: "+441010101010",
    email: "emma.davis@example.com",
    role: "standard_user",
    password: "randompassword19",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: 20,
    username: "random_user_20",
    first_name: "John",
    last_name: "Smith",
    phone_number: "+441111111111",
    email: "john.smith@example.com",
    role: "standard_user",
    password: "randompassword20",
    avatar: "https://randomuser.me/api/portraits/men/20.jpg",
  },
];
